# -*- coding: utf-8 -*-
"""Trabalho Final

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oW7-ee-65l8P2mwt7PMjf3_2clNvAQAU
"""

import datetime


class Compromisso: #classe que controla os compromissos

  def __init__(self, descricao, data, hora, duracao):
    self.descricao = descricao
    self.data = data
    self.hora = hora
    self.duracao = duracao


class Agenda: #classe que controla a agenda

  def __init__(self):
    self.compromissos = []

  def incluir_compromisso(self):
    descricao = input("Digite a descrição do compromisso: ")
    data = input("Digite a data do compromisso (formato: dd/mm/aaaa): ")
    hora = input("Digite a hora do compromisso (formato: hh:mm): ")
    duracao = int(input("Digite a duração do compromisso em minutos: "))

    # Verifica se já existe um compromisso agendado para a mesma data e horário
    for compromisso in self.compromissos:
      if compromisso.data == data and compromisso.hora == hora:
        print("Já existe um compromisso agendado para esta data e hora.")
        return

    # Cria o compromisso e adiciona na lista
    novo_compromisso = Compromisso(descricao, data, hora, duracao)
    self.compromissos.append(novo_compromisso)
    print("Compromisso agendado com sucesso!")

  def consultar_compromissos(self):
    data = input("Digite a data a ser consultada (formato: dd/mm/aaaa): ")
    hora = input(
      "Digite a hora a ser consultada (formato: hh:mm - opcional): ")

    compromissos_encontrados = [] 
    for compromisso in self.compromissos:
      if compromisso.data == data:
        if hora and compromisso.hora == hora:
          compromissos_encontrados.append(compromisso)
        elif not hora:
          compromissos_encontrados.append(compromisso)

    if compromissos_encontrados:
      for compromisso in compromissos_encontrados:
        print(
          f"Descrição: {compromisso.descricao} | Data: {compromisso.data} | Hora: {compromisso.hora} | Duração: {compromisso.duracao} minutos"
        )
    else:
      print("Agenda vazia.")

  def alterar_compromisso(self):
    data = input(
      "Digite a data do compromisso a ser alterado (formato: dd/mm/aaaa): ")
    hora = input(
      "Digite a hora do compromisso a ser alterado (formato: hh:mm): ")

    compromisso_encontrado = None
    for compromisso in self.compromissos:
      if compromisso.data == data and compromisso.hora == hora:
        compromisso_encontrado = compromisso
        break

    if compromisso_encontrado:
      descricao = input("Digite a nova descrição do compromisso: ")
      duracao = int(input("Digite a nova duração do compromisso em minutos: "))

      compromisso_encontrado.descricao = descricao
      compromisso_encontrado.duracao = duracao

      print("Compromisso alterado com sucesso!")
    else:
      print("Compromisso não encontrado.")

  def excluir_compromisso(self):
    data = input(
      "Digite a data do compromisso a ser excluído (formato d/mm/aaaa): ")
    hora = input(
      "Digite a hora do compromisso a ser excluído (formato: hh:mm): ")

    compromisso_encontrado = None
    for compromisso in self.compromissos:
      if compromisso.data == data and compromisso.hora == hora:
        compromisso_encontrado = compromisso
        break

    if compromisso_encontrado:
      self.compromissos.remove(compromisso_encontrado)
      print("Compromisso excluído com sucesso!")
    else:
      print("Compromisso não encontrado.")

  def listar_todos_compromissos(self):
    if self.compromissos:
      for compromisso in self.compromissos:
        print(
          f"Descrição: {compromisso.descricao} | Data: {compromisso.data} | Hora: {compromisso.hora} | Duração: {compromisso.duracao} minutos"
        )
    else:
      print("Agenda vazia.")

  def menu(self):
    while True:
      print("\n-- Agenda --")
      print("1. Incluir compromisso")
      print("2. Consultar compromisso")
      print("3. Alterar compromisso")
      print("4. Excluir compromisso")
      print("5. Listar todos os compromissos")
      print("6. Sair")

      opcao = int(input("Digite a opção desejada: "))

      if opcao == 1:
        self.incluir_compromisso()
      elif opcao == 2:
        self.consultar_compromissos()
      elif opcao == 3:
        self.alterar_compromisso()
      elif opcao == 4:
        self.excluir_compromisso()
      elif opcao == 5:
        self.listar_todos_compromissos()
      elif opcao == 6:
        break
      else:
        print("Opção inválida, tente novamente.")


# uso
agenda = Agenda()
agenda.menu()